import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/layouts/Header";
import { getCurrentSession } from "@/actions/auth";
import { SanityLive } from "@/sanity/lib/live";

const interFont = localFont({
	src: [
		{
			path: "./../assets/fonts/Inter-Thin.ttf",
			style: "normal",
			weight: "100",
		},
		{
			path: "./../assets/fonts/Inter-ExtraLight.ttf",
			style: "normal",
			weight: "200",
		},
		{
			path: "./../assets/fonts/Inter-Light.ttf",
			style: "normal",
			weight: "300",
		},
		{
			path: "./../assets/fonts/Inter-Regular.ttf",
			style: "normal",
			weight: "400",
		},
		{
			path: "./../assets/fonts/Inter-Medium.ttf",
			style: "normal",
			weight: "500",
		},
		{
			path: "./../assets/fonts/Inter-SemiBold.ttf",
			style: "normal",
			weight: "600",
		},
		{
			path: "./../assets/fonts/Inter-Bold.ttf",
			style: "normal",
			weight: "700",
		},
		{
			path: "./../assets/fonts/Inter-ExtraBold.ttf",
			style: "normal",
			weight: "800",
		},
		{
			path: "./../assets/fonts/Inter-Black.ttf",
			style: "normal",
			weight: "900",
		},
	],
});

export const metadata: Metadata = {
	title: "TEMU CLONE",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const { user } = await getCurrentSession();

	return (
		<html lang="en">
			<body className={`${interFont.className} antialiased bg-white min-h-[125vh]`}>
				<Header user={user} />
				{children}
				<SanityLive />
			</body>
		</html>
	);
}
